---
title: "EJERCICIOS TEMA 3"
author: "Christian Cadena"
date: "15/1/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# EJERCICIOS TEMA 3.2

## Pregunta 1:

Sea la matriz \ A y \ B :

$$A = \begin{pmatrix}
1 & 2 & 3 & 4\\
4 & 3 & 2 & 1\\
0 & 1 & 0 & 2\\
3 & 0 & 4 & 0
\end{pmatrix}$$

$$B = \begin{pmatrix}
4 & 3 & 2 & 1\\
0 & 3 & 0 & 4\\
1 & 2 & 3 & 4\\
0 & 1 & 0 & 2
\end{pmatrix}$$


### Respuesta en R de la pregunta 1:
```{r}
A=rbind(c(1,2,3,4), c(4,3,2,1), c(0,1,0,2), c(3,0,4,0))
B=rbind(c(4,3,2,1), c(0,3,0,4), c(1,2,3,4), c(0,1,0,1))

C=A%*%B
C
D=B%*%A
D
```
### Respuesta en Latex:

$$C = A*B = \begin{pmatrix}
1 & 2 & 3 & 4\\
4 & 3 & 2 & 1\\
0 & 1 & 0 & 2\\
3 & 0 & 4 & 0
\end{pmatrix} * 
\begin{pmatrix}
4 & 3 & 2 & 1\\
0 & 3 & 0 & 4\\
1 & 2 & 3 & 4\\
0 & 1 & 0 & 2
\end{pmatrix} = 
\begin{pmatrix}
`r C[1,1]` & `r C[1,2]` & `r C[1,3]` & `r C[1,4]`\\
`r C[2,1]` & `r C[2,2]` & `r C[2,3]` & `r C[2,4]`\\
`r C[3,1]` & `r C[3,2]` & `r C[3,3]` & `r C[3,4]`\\
`r C[4,1]` & `r C[4,2]` & `r C[4,3]` & `r C[4,4]`
\end{pmatrix}
$$

$$D = B*A = \begin{pmatrix}
4 & 3 & 2 & 1\\
0 & 3 & 0 & 4\\
1 & 2 & 3 & 4\\
0 & 1 & 0 & 2
\end{pmatrix} * 
\begin{pmatrix}
1 & 2 & 3 & 4\\
4 & 3 & 2 & 1\\
0 & 1 & 0 & 2\\
3 & 0 & 4 & 0
\end{pmatrix} = 
\begin{pmatrix}
`r D[1,1]` & `r D[1,2]` & `r D[1,3]` & `r D[1,4]`\\
`r D[2,1]` & `r D[2,2]` & `r D[2,3]` & `r D[2,4]`\\
`r D[3,1]` & `r D[3,2]` & `r D[3,3]` & `r D[3,4]`\\
`r D[4,1]` & `r D[4,2]` & `r D[4,3]` & `r D[4,4]`
\end{pmatrix}
$$

## PREGUNTA 2:

Sea: \ dni =(1,7,1,6,1,8,6,5,3,4)

### Respuesta en R:

```{r}
dni = c(1,7,1,6,1,8,6,5,3,4)
dni
dni2 = dni^2
dni2
cumsum(dni)

```
### Respuestas en Latex:

$$dni2 = dni^{2} = \begin{pmatrix}
1 & 7 & 1 & 6 & 1 & 8 & 6 & 5 & 3 & 4\\
\end{pmatrix}^{2} = 
\begin{pmatrix}
`r dni[1]` & `r dni[2]` & `r dni[3]` & `r dni[4]` & `r dni[5]` & `r dni[6]` & `r dni[7]`
 & `r dni[8]` & `r dni[9]` & `r dni[10]`\\
\end{pmatrix}
$$

## PREGUNTA 3:

Sea: \ nombre = (C,H,R,I,S,T,I,A,N,C,A,D,E,N,A)


### En R:
```{r}
nombre = c("C","H","R","I","S","T","I","A","N","C","A","D","E","N","A")
nombre
nombre1 = nombre[c(10,11,12,13,14,15)]
nombre1
order1 = ordered(nombre1)
order1

#v=1:26
#order2 = ordered(c(1,3,8,9,9,14,18,19,20),levels = v, labels = #c("A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X#","Y","Z"))
#order

```







