---
title: "R&Python"
author: "Christian Cadena"
date: "10/1/2020"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## RETICULATE: Una librería para usar funciones de R y PYTHON, se usa modulos, clases y funciones de python

```{r}
library(reticulate)
use_python("/Users/C.Cadena/Anaconda3/python.exe")
#py_install("nombre del paquete a instalar"), esto instala en anaconda, pero si no esta el directorio de anaconda lo instalara en el python de R
os  <- import("os")
os$listdir(".")
```

```{r}
source_python("add.py")
add(3,4)
```
# El siguiente es conversion de objetos de un lenguaje a otro:
```{r}
np <- import("numpy", convert = FALSE) #No se hace una conversion de objetos python a R, se va a trabajar con objetos python nativos.

x <- np$array(c(1:4)) #
sum <- x$cumsum() # Estoy llamando a la funcion cumsum del paquete numpy, invocado sobre x que es un objeto array de python pasado a R.

print(sum) # sum sera una variable de python. Es una lista con corchete, en R hay vectores.

# Conversion de objetos explicita:
py_to_r(sum)
```

# La consulta:

```{r}
help("py_to_r")
py_help(os$chdir)

```

# Crear en R un objeto de python: 

```{r}
a <- np_array(c(1:10), order="C")
a
```

```{r}
datos <- iris
head(datos)
datos_py <- r_to_py(datos)
```

```{python}
import numpy as np
import pandas as pd

r.datos_py.head
```

## Sparce Matrix

```{r}
library(Matrix)
N <- 6
set.seed(12)
sparce_mat <- sparseMatrix(
  i = sample(N, N, replace = F),
  j = sample(N, N, replace = F),
  x = runif(N),
  dims = c(N,N)
)
sparce_mat
sparce_mat_py <- r_to_py(sparce_mat)
```

```{python}
r.sparce_mat_py
```

```{r}
py_to_r(sparce_mat_py)
```




